##
## Copyright (C) by Innovative Computing Laboratory
##     See copyright in top-level directory
##

COMPONENT_PREFIX=$1
COMPONENT_SUBSIRS=$(ls -d $COMPONENT_PREFIX/*/)

echo "## File automatically generated by configure. Do not edit" >& $COMPONENT_PREFIX/Makefile.mk
echo "

##
## Copyright (C) by Innovative Computing Laboratory
##     See copyright in top-level directory
##

" >> $COMPONENT_PREFIX/Makefile.mk

for subdir in $COMPONENT_SUBSIRS ; do
    subdir=$(basename `echo $subdir | sed 's/\/$//'`)
    echo 'include $(top_srcdir)/src/components/'$subdir'/Makefile.mk' >> "$COMPONENT_PREFIX/Makefile.mk"
done
